on: push
name: 🚀 Deploy app on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: Deploy to cPanel
      id: deploy
      uses: pinkasey/cpanel-deploy-action@v1.0.0
      with:
        hostname: 'https://hostname.example.com'
        repository_root: '/home/my_account/repositories/my_repository'
        branch: main
        cpanel_token: '${{ secrets.CPANEL_TOKEN }}'
        
    - name: echo deploy-duration
      run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"

