on: push
name: 🚀 Deploy app on push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.8
      with:
        host: ${{ secrets.FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 21 # optional, default is: 21
        username: ${{ secrets.FTP_USERNAME }} # FTP username
        password: ${{ secrets.FTP_PASSWORD }} # FTP password
        passive: true # optional
